In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [3]:
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
mx_1s=np.ones(5)

In [6]:
print(mx_1s)

[1. 1. 1. 1. 1.]


In [7]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
mx_1s=np.ones(9)

In [9]:
print(mx_1s)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
mx_1s.dtype

dtype('float64')

In [11]:
mx_1s=np.ones((3,4))

In [12]:
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
mx_1s=np.ones((4,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
mx_1s=np.ones((3,4),dtype=int)

In [15]:
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
mx_0s = np.zeros((4,5))
print(mx_0s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
mx_2s = np.ones((2,3))
print(mx_2s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
mx_2s = np.ones((2,3),dtype=bool)
print(mx_2s)

[[ True  True  True]
 [ True  True  True]]


In [19]:
mx_0s = np.zeros((4,5),dtype=bool)
print(mx_0s)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [20]:
mx_4s = np.zeros((4,5))
print(mx_4s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
mx_0s = np.zeros((4,5),dtype=bool)
print(mx_0s)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [22]:
mx_0s = np.zeros((4,5),dtype=str)
print(mx_0s)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [23]:
mx_0s = np.zeros((4,5),dtype=int)
print(mx_0s)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [24]:
mx_0s = np.zeros((4,5),dtype=float)
print(mx_0s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
em_str=''
print(bool(em_str))

False


In [26]:
em_mx = np.empty((3,3))

In [27]:
print(em_mx)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
