# Python Numpy Array Slicing(:)

In [1]:
import numpy as np

In [2]:
mx = np.arange (1,51).reshape(5,10)

In [3]:
print(mx)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [4]:
mx[0,0]

1

In [5]:
mx[1,1]

12

In [6]:
mx[2,2]

23

In [7]:
mx[2,3]

24

In [8]:
mx[3,3]

34

In [9]:
mx[4,4]

45

In [10]:
mx[4,9]

50

In [11]:
mx[2,2].ndim

0

In [12]:
mx[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
mx[:,0]

array([ 1, 11, 21, 31, 41])

In [14]:
mx[:,4]

array([ 5, 15, 25, 35, 45])

In [15]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41]])

In [16]:
mx[:,0:1].ndim

2

In [17]:
mx[1:4,1:2]

array([[12],
       [22],
       [32]])

In [18]:
mx[1:4,1:6]

array([[12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36]])

In [19]:
mx[1:4,0:10]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [20]:
mx[0:5,0:10]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [21]:
mx[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43]])

In [22]:
mx[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
mx[::]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [24]:
mx.itemsize

4

In [25]:
mx.dtype

dtype('int32')

In [26]:
32/8

4.0

In [27]:
45/9

5.0