# Numpy Functions:

In [1]:
import numpy as np

# Arange

In [2]:
#np.arrange(star,Ende steps)
arr_1d = np.arange(1,25)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [3]:
even_ar = np.arange(1,25,5)
print(even_ar)

[ 1  6 11 16 21]


In [4]:
even_ar = np.arange(1,25,2)
print(even_ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [5]:
even_ar = np.arange(1,26,2)
print(even_ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]



# Linspace()

In [6]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [7]:
np.linspace(1,10,2)

array([ 1., 10.])

In [8]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [9]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# Reshape()

In [10]:
ar_2d = arr_1d.reshape(2,12)
print(ar_2d)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [11]:
ar_2d = arr_1d.reshape(4,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [12]:
ar_3d = arr_1d.reshape(2,4,3)

In [13]:
print(ar_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [14]:
ar=np.arange(5,11).reshape(2,3)

In [15]:
print(ar)

[[ 5  6  7]
 [ 8  9 10]]


# Ravel

In [16]:
ar.ravel()

array([ 5,  6,  7,  8,  9, 10])

# Flatten()

In [17]:
ar.flatten()

array([ 5,  6,  7,  8,  9, 10])

# Transpose()

In [18]:
ar.transpose()

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

In [19]:
ar.T

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])