# Mathematics Operation Using Numpy

In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(1,17).reshape(4,4)
arr_2 = np.arange(1,17).reshape(4,4)
print(arr_1)
print(arr_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr_1 + arr_2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [4]:
np.add(arr_1,arr_2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [5]:
arr_1-arr_2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.subtract(arr_1,arr_2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
arr_1/arr_2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.divide(arr_1,arr_2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr_1*arr_2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [10]:
np.multiply(arr_1,arr_2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [11]:
arr_1@arr_2

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [12]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
arr_1.max()

16

In [14]:
arr_1.argmax()

15

In [15]:
arr_1.max(axis=0)

array([13, 14, 15, 16])

In [16]:
arr_1.max(axis=1)

array([ 4,  8, 12, 16])

In [17]:
arr_1.min()

1

In [18]:
arr_1.min(axis=0)

array([1, 2, 3, 4])

In [19]:
arr_1.argmin()

0

In [20]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
np.sum(arr_1)

136

In [22]:
np.sum(arr_1,axis=0)

array([28, 32, 36, 40])

In [23]:
np.sum(arr_1,axis=1)

array([10, 26, 42, 58])

In [24]:
np.mean(arr_1)

8.5

In [25]:
np.sqrt(arr_1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [26]:
np.std(arr_1)

4.6097722286464435

In [27]:
np.exp(arr_1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06]])

In [28]:
np.log(arr_1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872]])

In [29]:
np.log10(arr_1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125],
       [1.11394335, 1.14612804, 1.17609126, 1.20411998]])