# Random Sampling With Numpy

In [8]:
import numpy as np
import random as rd

In [11]:
np.random.random(1)

array([0.85780614])

In [13]:
np.random.random(2)

array([0.58510607, 0.51599948])

In [14]:
np.random.random((1,2))

array([[0.47411889, 0.13788332]])

In [15]:
np.random.random((2,2))

array([[0.81849698, 0.63487121],
       [0.21680329, 0.78507051]])

In [16]:
np.random.random(((3,3)))

array([[0.12071082, 0.49652215, 0.25663798],
       [0.62129978, 0.99431319, 0.1241877 ],
       [0.2401118 , 0.30083097, 0.19913241]])

In [17]:
np.random.random((2,4))

array([[0.25890395, 0.53922482, 0.12489229, 0.52536597],
       [0.760554  , 0.98318431, 0.13201066, 0.24245335]])

In [38]:
np.random.randint(1)

0

In [39]:
np.random.randint(2)

0

In [40]:
np.random.randint(10)

4

In [41]:
np.random.randint((1,1))

array([0, 0])

In [42]:
np.random.randint((2,2))

array([0, 1])

In [23]:
np.random.randint((1,2))

array([0, 1])

In [24]:
np.random.randint((2))

1

In [25]:
np.random.randint((1))

0

In [26]:
np.random.randint((10))

9

In [43]:
np.random.randint(1,2)

1

In [57]:
np.random.randint(1,5)

4

In [48]:
np.random.randint(1,4)

3

In [55]:
np.random.randint(1,6)

1

In [59]:
np.random.randint(1,7,(5,5))

array([[6, 4, 6, 2, 1],
       [1, 6, 5, 4, 3],
       [1, 4, 1, 4, 6],
       [3, 6, 3, 4, 5],
       [6, 5, 3, 5, 2]])

In [58]:
np.random.randint(1,9,(2,2))

array([[8, 3],
       [2, 8]])

In [63]:
np.random.randint(1,5,(9,4,4))

array([[[2, 3, 3, 1],
        [4, 2, 2, 2],
        [3, 1, 4, 4],
        [1, 4, 2, 4]],

       [[3, 2, 1, 1],
        [4, 3, 4, 1],
        [3, 3, 1, 1],
        [1, 1, 1, 3]],

       [[2, 2, 1, 1],
        [4, 3, 4, 4],
        [4, 3, 1, 4],
        [3, 1, 2, 4]],

       [[2, 1, 3, 1],
        [3, 4, 3, 1],
        [1, 4, 4, 3],
        [4, 3, 1, 4]],

       [[4, 1, 3, 3],
        [4, 2, 2, 4],
        [2, 4, 1, 2],
        [2, 4, 2, 1]],

       [[2, 3, 4, 4],
        [1, 2, 3, 2],
        [2, 4, 4, 4],
        [4, 1, 2, 1]],

       [[1, 1, 4, 4],
        [3, 3, 1, 4],
        [1, 4, 2, 3],
        [1, 4, 3, 3]],

       [[2, 3, 1, 3],
        [1, 1, 3, 1],
        [2, 3, 1, 2],
        [2, 1, 2, 2]],

       [[4, 2, 4, 3],
        [1, 4, 1, 3],
        [3, 3, 1, 3],
        [1, 3, 4, 4]]])

In [65]:
np.random.seed(5)
np.random.randint(1,5,(2,4,4))

array([[[4, 3, 4, 2],
        [3, 3, 1, 2],
        [1, 1, 4, 3],
        [4, 1, 3, 1]],

       [[4, 1, 4, 2],
        [2, 4, 1, 4],
        [1, 2, 4, 2],
        [4, 3, 1, 3]]])

In [66]:
np.random.seed(5)
np.random.randint(1,5,(2,4,4))

array([[[4, 3, 4, 2],
        [3, 3, 1, 2],
        [1, 1, 4, 3],
        [4, 1, 3, 1]],

       [[4, 1, 4, 2],
        [2, 4, 1, 4],
        [1, 2, 4, 2],
        [4, 3, 1, 3]]])

In [67]:
2**32-1

4294967295

In [68]:
np.random.rand(5)

array([0.41423502, 0.29607993, 0.62878791, 0.57983781, 0.5999292 ])

In [69]:
np.random.rand(5,2)

array([[0.26581912, 0.28468588],
       [0.25358821, 0.32756395],
       [0.1441643 , 0.16561286],
       [0.96393053, 0.96022672],
       [0.18841466, 0.02430656]])

In [70]:
np.random.rand(2,5)

array([[0.20455555, 0.69984361, 0.77951459, 0.02293309, 0.57766286],
       [0.00164217, 0.51547261, 0.63979518, 0.9856244 , 0.2590976 ]])

In [71]:
np.random.rand(2,5)

array([[0.80249689, 0.87048309, 0.92274961, 0.00221421, 0.46948837],
       [0.98146874, 0.3989448 , 0.81373248, 0.5464565 , 0.77085409]])

In [72]:
np.random.seed(10)
np.random.rand(2,5)

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [74]:
np.random.seed(10)
np.random.rand(2,5)

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [75]:
np.random.seed(5)
np.random.rand(2,5)

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123]])

In [76]:
np.random.seed(5)
np.random.rand(2,5)

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123]])

In [77]:
np.random.randn(2,2)

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651]])

In [78]:
vansh = [1,2,5,4,9]
np.random.choice(vansh)

9

In [79]:
vansh = [1,2,5,4,9]
np.random.choice(vansh)

5

In [80]:
vansh = [1,2,5,4,9]
np.random.seed(10)
np.random.choice(vansh)

2

In [81]:
vansh = [1,2,5,4,9]
np.random.seed(10)
np.random.choice(vansh)

2

In [89]:
for i in range(10):
    print(np.random.choice(vansh))

1
2
1
4
4
5
1
1
9
4


In [91]:
vansh

[1, 2, 5, 4, 9]

In [92]:
np.random.permutation(vansh)

array([1, 4, 5, 9, 2])

In [93]:
np.random.permutation(vansh)

array([5, 4, 1, 9, 2])

In [94]:
np.random.permutation(vansh)

array([1, 5, 2, 4, 9])

In [99]:
np.random.permutation(vansh)

array([4, 5, 2, 1, 9])